//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscribeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribers
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string DateSubscribed { get; set; }
    }
}
